# .linkspector.yml
dirs:
  - docs
  - i18n\fr\docusaurus-plugin-content-docs
fileExtensions:
  - md
  - mdx
# This forces the tool to treat all links with this as the root for relative paths
baseUrl: "/" 
# You can ignore specific patterns if needed
ignorePatterns:
  - pattern: "http://localhost:.*"
  - pattern: "https://doi.org/*"
  - pattern: "https://scicrunch.org/*"
  - pattern: "https://rrid.site/*"
  - pattern: "/doi/"